"""Give each Art Pack submod its own copy of its clip, stamped so the bytes are unique.

The pack generated by `generate_art_pack.py` points at the Ashes of War author's folders
through `overrideAnimationsFolder` and copies nothing. The author ships 96 art animations
backed by only 56 unique files, so almost every named art is byte-identical to a stance
moveset clip. OAR's duplicate filter -- on in Nolvus, and not ours to switch off -- collapses
two submods that reference the same bytes into one object and leaves the loser with an empty
clip generator. Which one loses is decided by four async parse workers, so the victim moves
between launches. That is weapon-arts ticket 15; ADR-0017 is the decision to stop sharing bytes.

This script copies each art's clip into its own submod and appends one annotation to it, which
changes the hash and makes the collision impossible.

The stamp carries the submod's name rather than a single shared token. Two of our own arts
(Pirate's Slash and Wind Slice) resolve to the same author file, so one shared stamp would
leave those two identical to each other -- the same defect, one layer in.

The stamp sits at the clip's own duration, the last instant it can occupy. Nothing registers
for the name, and an art that is cut short never reaches it at all.

Run with --verify after a run (or on its own) to check what is on disk: every submod owning a
clip, every hash distinct, and no clip still matching the author's original.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

CLIP_NAME = "AABL_Attack_A.hkx"
STAMP_PREFIX = "SH2_PackStamp_"


def slug(name: str) -> str:
    """A stamp token: annotation lines are space delimited, so the name cannot keep spaces."""
    return re.sub(r"[^A-Za-z0-9]+", "_", name).strip("_")


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def read_config(submod: Path) -> dict:
    return json.loads((submod / "config.json").read_text(encoding="utf-8-sig"))


def resolve_source(submod: Path, oar_root: Path) -> Path | None:
    """The clip a pointer submod is currently borrowing, or None once it owns its own."""
    override = read_config(submod).get("overrideAnimationsFolder")
    if not override:
        return None
    return (oar_root / override.replace("../", "")).resolve() / CLIP_NAME


def stamp(clip: Path, token: str, anno_cli: Path) -> None:
    """Append one annotation at the clip's duration and write it back through hkxc-anno-cli."""
    with tempfile.TemporaryDirectory() as tmp:
        dump = Path(tmp) / "anno.txt"
        run(anno_cli, ["dump", "-i", str(clip), "-o", str(dump)])
        text = dump.read_text()

        duration = re.search(r"^# duration: ([0-9.]+)", text, re.M)
        if not duration:
            raise RuntimeError(f"no duration header in the dump of {clip}")
        if STAMP_PREFIX in text:
            raise RuntimeError(f"{clip} is already stamped; re-run from a clean pack")

        text = re.sub(r"^# annotations: (\d+)",
                      lambda m: f"# annotations: {int(m.group(1)) + 1}", text, count=1, flags=re.M)
        if not text.endswith("\n"):
            text += "\n"
        text += f"{float(duration.group(1)):.6f} {STAMP_PREFIX}{token}\n"
        dump.write_text(text)

        run(anno_cli, ["update", "-a", str(dump), "-i", str(clip)])


def run(exe: Path, args: list[str]) -> None:
    result = subprocess.run([str(exe), *args], capture_output=True, text=True)
    if result.returncode != 0:
        raise RuntimeError(f"{exe.name} {args[0]} failed:\n{result.stdout}\n{result.stderr}")


def apply(pack: Path, oar_root: Path, anno_cli: Path) -> int:
    submods = sorted(d for d in pack.iterdir() if d.is_dir() and (d / "config.json").is_file())
    done = skipped = 0
    for submod in submods:
        source = resolve_source(submod, oar_root)
        if source is None:
            skipped += 1
            continue
        if not source.is_file():
            print(f"  MISSING SOURCE  {submod.name} -> {source}")
            continue

        clip = submod / CLIP_NAME
        shutil.copy2(source, clip)
        stamp(clip, slug(submod.name), anno_cli)

        config = read_config(submod)
        config.pop("overrideAnimationsFolder")
        (submod / "config.json").write_text(json.dumps(config, indent=4) + "\n", encoding="utf-8")

        done += 1
        print(f"  stamped  {submod.name:24s} {sha256(clip)[:12]}  <- {source.parent.name}")

    print(f"\n{done} submods now own their clip; {skipped} had no override and were left alone.")
    return done


def verify(pack: Path, oar_root: Path) -> bool:
    """On-disk truth: who owns a clip, are the hashes distinct, and do any still match upstream."""
    owned: dict[str, list[str]] = {}
    pointers: list[str] = []
    for submod in sorted(d for d in pack.iterdir() if d.is_dir()):
        config_path = submod / "config.json"
        if not config_path.is_file():
            continue
        if read_config(submod).get("overrideAnimationsFolder"):
            pointers.append(submod.name)
        clip = submod / CLIP_NAME
        if clip.is_file():
            owned.setdefault(sha256(clip), []).append(submod.name)

    upstream = {sha256(c) for c in oar_root.rglob(CLIP_NAME)
                if pack not in c.parents}

    total = sum(len(v) for v in owned.values())
    collisions = {h: v for h, v in owned.items() if len(v) > 1}
    shared = {h: v for h, v in owned.items() if h in upstream}

    print(f"submods owning a clip : {total}")
    print(f"distinct hashes       : {len(owned)}")
    print(f"still pointing        : {len(pointers)}{' ' + str(pointers) if pointers else ''}")
    for h, names in collisions.items():
        print(f"  COLLISION  {h[:12]}  {names}")
    for h, names in shared.items():
        print(f"  MATCHES AUTHOR  {h[:12]}  {names}")

    ok = not collisions and not shared and total > 0
    print("\nVERIFY:", "clean -- every clip is unique and none matches the author's"
          if ok else "FAILED -- see the lines above")
    return ok


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--pack", required=True, type=Path,
                        help="the SpellHotbar2Arts directory holding the submods")
    parser.add_argument("--oar-root", required=True, type=Path,
                        help="the OpenAnimationReplacer directory the overrides resolve against")
    parser.add_argument("--anno-cli", type=Path, default=Path(r"C:\Tools\SkyrimHKX\hkxc-anno-cli.exe"))
    parser.add_argument("--verify", action="store_true", help="check the pack on disk and exit")
    args = parser.parse_args()

    if not args.pack.is_dir():
        print(f"no such pack directory: {args.pack}", file=sys.stderr)
        return 2

    if args.verify:
        return 0 if verify(args.pack, args.oar_root) else 1

    if not args.anno_cli.is_file():
        print(f"hkxc-anno-cli not found at {args.anno_cli}", file=sys.stderr)
        return 2

    apply(args.pack, args.oar_root, args.anno_cli)
    print()
    return 0 if verify(args.pack, args.oar_root) else 1


if __name__ == "__main__":
    raise SystemExit(main())
